#!/usr/bin/env bash
# script that configures a Nginx server to have a custom 404

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i '/listen \[::\]:80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i '/listen \[::\]:80 default_server;/a error_page 404 \/custom_404.html;' /etc/nginx/sites-available/default
sudo sed -i '/custom_404.html;/a location = \/custom_404.html {root /usr/share/nginx/html;internal;}' /etc/nginx/sites-available/default
sudo service nginx restart
