#!/usr/bin/env bash
# double the number of webservers
Redirection="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGU1wu4;\n\t}\n"
error="\\\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
apt-get -y update
apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "35i $Redirection" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i "38i $error" /etc/nginx/sites-available/default
sed -i "53i \\\t\tadd_header X-Server-By $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
