#!/usr/bin/env bash
# double the number of webservers
apt-get -y update
apt-get -y install nginx
sed -i "53i \\\t\tadd_header X-Server-By $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
