#!/usr/bin/env bash
# configures Nginx 

apt-get update
apt-get -y install nginx

service nginx start

config="/etc/nginx/sites-available/default"
text="server {\n\tadd_header X-Served-By \$hostname;"
sed -i "0,/server {/s//$text/" "$config"

service nginx restart
