#!/usr/bin/env bash
# Run nginx as nginx
sudo netstat -tulp | grep LISTEN
sudo pkill -9 apache2
sudo chown -R nginx:nginx /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u "nginx" bash -c 'service nginx restart'
